### ISSUE TITLE
import/export issues

### ISSUE THREAD

**Issue by jondor** [Ariadne-CMS/ariadne#68] opened 2015-10-07 14:40 UTC
The import from an 9.1 to a 2.7.8 server doesn't work.  Here's an overview from the issues. This is serious as it does prevent the upgrading from older systems..

9.1 -> 8.4: probleem foutmelding EN skipped data
export(/) to (/trash/)
processing(/trash/)	(no overwrite)
processing(/trash/photo/)	(saving )
ERROR (ERROR: Mysql: 1054: Unknown column 'AR_scope' in 'field list')
skipping (/trash/photo/1456463-large.jpg/)
skipping (/trash/photo/nothumb/)
clearing cache on /trash/photo/.

9.1 -> 2.7.8: Probleem. Skipped content
export(/) to (/trash/)
processing(/trash/)	(no overwrite)
processing(/trash/photo/)	(saving )	skipping (/trash/photo/1456463-large.jpg/)
skipping (/trash/photo/nothumb/)
clearing cache.

8.4->2.7.8: Geen probleem
export(/) to (/trash/)
processing(/trash/)	(no overwrite)
processing(/trash/images/)	(ok)
processing(/trash/images/ajax-loader.gif/)	(ok)
file(nl_file) no update
file(file) no update
processing(/trash/images/application/)	(ok)
processing(/trash/images/application/jpg.png/)	(ok)
file(nl_file) no update
file(file) no update
etc.. 

2.7.8 -> 8.4: Geen probleem
export(/) to (/trash/)
processing(/trash/)	(no overwrite)
processing(/trash/layout2011/)	(saving )
exporting/importing templates
template [pbookmark][body.html][any]
template [pbookmark][cContent.html][any]
template [pbookmark][view.html][any]
template [pbookmark][list.html][any]
template [pfile][fulltext.list.html][any]
template [pfile][list.html][any]
etc.

2.7.8 -> 9.1
Seems to work. Data is there..

8.4 -> 9.1. Has issues, but this testcase seems to work. An other testcase yesterday didn't.
export(/) to (/projects/)
processing(/projects/)	(no overwrite)
processing(/projects/images/)	(updating)
processing(/projects/images/ajax-loader.gif/)	(updating)
file(file) ERROR: Could not open file
file(nl_file) created
processing(/projects/images/application/)	(updating)
processing(/projects/images/application/jpg.png/)	(updating)
file(file) ERROR: Could not open file
file(nl_file) created
processing(/projects/images/application/mp3.png/)	(updating)
file(file) ERROR: Could not open file
file(nl_file) created
processing(/projects/images/application/msword.png/)	(updating)
file(file) ERROR: Could not open file
file(nl_file) created
processing(/projects/images/application/pdf.png/)	(updating)
file(file) ERROR: Could not open file
file(nl_file) created

**Comment by jondor** [comment] 2015-10-07 20:02
ayes, and 9.1 to 9.1 had issues too..

**Comment by mjrider** [comment] 2015-10-10 07:27
Could you supply a broken .ax file ? i  can not reproduce the problem here localy on a 9.2 release
9.1 was a broken release so please use 9.2 for testing
i suspect that it is a local config problem, so could you give us as much information as possible about system you are testing on.

**Comment by jondor** [comment] 2015-10-12 09:08
The file which started this issue was send last week to support@. incl. extra info etc.

**Comment by poef** [comment] 2016-01-07 13:39
We couldn't reproduce the problem with the given file on the latest stable release. So the problem is fixed. Closing.

**Closed** 2016-01-07 13:40 UTC
