### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by jondor** [Ariadne-CMS/ariadne#24] opened 2015-05-12 12:13 UTC
Did a clean installation once again.. Here's my current list of minor issues

* mcrypt is installed, but doesn't seem to be detected
* please add to the docu to use: "pear install pear install Archive_Tar"
* please add to the docu to use: "pear install -f VersionControl_SVN"
*   svn co https://svn.muze.nl/svn/muze/pear/VersionControl /usr/share/php/VersionControl ask for a login. So I can't install the right SVN stuff, which means that detections works (got a check which I didn't set) but will not work.. 

* an oldy, but it's still not fixed: The path in /www/ariadne.inc-unix. Does anyone actually use: /usr/local/lib/ariadne/lib ? /var/www/ariadne/lib or /opt/website/site/lib would make more sense.

**Comment by mjrider** [comment] 2015-05-12 12:38
mcrypt:
could you verify that it is also loaded in php, and what doesn't work atm, when it is not installed?

please add to the docu to use: "pear install pear install Archive_Tar"
we are working on including all required pear libs in composer

please add to the docu to use: "pear install -f VersionControl_SVN":
ariadne is incompatible with the pear version of VersionControl, we are working on the fix for that

the svn issue will be fixed, it should be public readable

and for the oldy, does it even matter which path we have there, the only sensible alternative is something like /path/to/checkout/of/ariadne/lib

PS. we prever 1 issue per issue, this makes it easier to track what is the status of issues

**Comment by mjrider** [comment] 2015-05-12 12:53
svn seems to be a client specific problem, travis is able to checkout the svn repository without any problems

**Comment by mjrider** [comment] 2015-05-22 08:32
could you try the versioncontrol checkout again, i think i fixed the problem

**Comment by mjrider** [comment] 2015-06-02 09:51
tar archive is included in the master branch, 
versioncontrol_svn is included in e952a06803d40bc182c9df18e5728a55011350ba.
our svn server has been fixed, so the checkout mentioned in the documentation is possible again.

for the mcrypt issue, please open a seperate issue describing the problem and the reproductive steps.

issue closed

**Closed by mjrider** 2015-06-02 09:51 UTC
Labels: question
